export const data = [
  {
    id: "schedule-1",
    date: "2024-11-17",
    timeSlots: [
      {
        id: "timeSlot-1-1",
        start_time: "09:00:00",
        end_time: "10:00:00",
        price: 50.0,
        type: "audio",
        clinic_id: null,
      },
      {
        id: "timeSlot-1-2",
        start_time: "10:30:00",
        end_time: "11:30:00",
        price: 75.0,
        type: "video",
        clinic_id: null,
      },
      {
        id: "timeSlot-1-3",
        start_time: "14:00:00",
        end_time: "15:00:00",
        price: 100.0,
        type: "clinic",
        clinic_id: "clinic-1",
      },
    ],
  },
  {
    id: "schedule-2",
    date: "2024-11-20",
    timeSlots: [
      {
        id: "timeSlot-2-1",
        start_time: "09:00:00",
        end_time: "10:00:00",
        price: 50.0,
        type: "audio",
        clinic_id: null,
      },
      {
        id: "timeSlot-2-2",
        start_time: "10:30:00",
        end_time: "11:30:00",
        price: 75.0,
        type: "video",
        clinic_id: null,
      },
      {
        id: "timeSlot-2-3",
        start_time: "14:00:00",
        end_time: "15:00:00",
        price: 100.0,
        type: "clinic",
        clinic_id: "clinic-2",
      },
    ],
  },
  {
    id: "schedule-3",
    date: "2024-11-23",
    timeSlots: [
      {
        id: "timeSlot-3-1",
        start_time: "09:00:00",
        end_time: "10:00:00",
        price: 50.0,
        type: "audio",
        clinic_id: null,
      },
      {
        id: "timeSlot-3-2",
        start_time: "10:30:00",
        end_time: "11:30:00",
        price: 75.0,
        type: "video",
        clinic_id: null,
      },
      {
        id: "timeSlot-3-3",
        start_time: "14:00:00",
        end_time: "15:00:00",
        price: 100.0,
        type: "clinic",
        clinic_id: "clinic-3",
      },
    ],
  },
  {
    id: "schedule-4",
    date: "2024-11-26",
    timeSlots: [
      {
        id: "timeSlot-4-1",
        start_time: "09:00:00",
        end_time: "10:00:00",
        price: 50.0,
        type: "audio",
        clinic_id: null,
      },
      {
        id: "timeSlot-4-2",
        start_time: "10:30:00",
        end_time: "11:30:00",
        price: 75.0,
        type: "video",
        clinic_id: null,
      },
      {
        id: "timeSlot-4-3",
        start_time: "14:00:00",
        end_time: "15:00:00",
        price: 100.0,
        type: "clinic",
        clinic_id: "clinic-4",
      },
    ],
  },
  {
    id: "schedule-5",
    date: "2024-11-29",
    timeSlots: [
      {
        id: "timeSlot-5-1",
        start_time: "09:00:00",
        end_time: "10:00:00",
        price: 50.0,
        type: "audio",
        clinic_id: null,
      },
      {
        id: "timeSlot-5-2",
        start_time: "10:30:00",
        end_time: "11:30:00",
        price: 75.0,
        type: "video",
        clinic_id: null,
      },
      {
        id: "timeSlot-5-3",
        start_time: "14:00:00",
        end_time: "15:00:00",
        price: 100.0,
        type: "clinic",
        clinic_id: "clinic-5",
      },
    ],
  },
];
